image: blejzu/gcc-cmake-sdl:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal
  TEST_REPORTS: /tmp/test-reports

build:
  stage: build
  script: 
    - .circleci/build.sh Debug
  artifacts:
    paths:
      - build-Debug
      - /tmp/shmup_tests

test:
  stage: test
  script: 
    - .circleci/test.sh Debug
  artifacts:
    paths:
      - /tmp/test-reports