version: 2
jobs:
  build:
    environment:
      TEST_REPORTS: /tmp/test-reports
    docker:
      - image: blejzu/gcc-cmake-sdl:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Debug build
          command: sh .circleci/build.sh Debug
      - run:
          name: Test Debug
          command: sh .circleci/test.sh Debug
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/test-reports
          destination: tests
      - run:
          name: Release build
          command: sh .circleci/build.sh Release
